# Generated by Django 5.0.1 on 2024-02-04 07:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perspectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('upboat', models.IntegerField()),
                ('downboat', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackathon_2024.perspectives')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackathon_2024.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackathon_2024.events')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackathon_2024.tags')),
            ],
        ),
        migrations.AddField(
            model_name='perspectives',
            name='tags',
            field=models.ManyToManyField(through='blackathon_2024.Tag_P', to='blackathon_2024.tags'),
        ),
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(through='blackathon_2024.Tag_E', to='blackathon_2024.tags'),
        ),
    ]
